# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-16.04' # other options: 'macOS-10.13', 'vs2017-win2016'

variables:
  buildConfiguration: 'Release'
  dockerId: mrdevops1
  imageName: dotnet-docker-image

steps:
- script: |
    docker build -t $(dockerId)/$(imageName) .
    echo  "$env:SECRET" | docker login -u $(dockerId) --password-stdin
    docker push $(dockerId)/$(imageName)

  env:
    SECRET: $(dockerPassword)        # Define dockerPassword in the Variables tab of this pipeline in Pipelines page of web interface 

  displayName: 'docker dotnet build $(buildConfiguration)'

  

#- script: dotnet build --configuration $(buildConfiguration)
  




