# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-16.04' # other options: 'macOS-10.13', 'vs2017-win2016'

variables:
  buildConfiguration: 'Release'
  dockerId: mrdevops1  # Replace with your Docker ID for Docker Hub or the admin user name for the Azure Container Registry
  imageName: dotnet-docker-image  # Replace with the name of the image you want to publish

env:
    pswd: $(dockerPassword)        # Define dockerPassword in the Variables tab of this pipeline in Pipelines page of web interface 

steps:
- script: |
    docker build -t $(dockerId)/$(imageName) .
    docker login -u $(dockerId) -p $(pswd)
    docker push $(dockerId)/$(imageName)

  displayName: 'docker dotnet build $(buildConfiguration)'

  

#- script: dotnet build --configuration $(buildConfiguration)
  




